src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 */
class Property
{
    const HEAT = [
        0 => 'Electric',
        1 => 'Gas'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min="10", max="300")
     */
    private $surface;

    /**
     * @ORM\Column(type="smallint")
     */
    private $rooms;

    /**
     * @ORM\Column(type="smallint")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="smallint")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
      */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
        @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    /**
     * scale defined number of int after comma, precision defined total number of int
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $lng;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;
        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;
        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;
        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;
        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;
        return $this;
    }

    /**
     * Get euro formatted price of property
     * @return string
     */
    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;
        return $this;
    }

    /**
     * Get string description of heat
     * @return string
     */
    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;
        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;
        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;
        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;
        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }
        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;
        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?Picture
    {
        if ($this->pictures->isEmpty()) {
            return null;
        }
        return $this->pictures->first();

    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param $pictureFiles
     * @return Property
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach ($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            // Add Option  (ManyToMany)
            // Enable several options to be selected for one Property,
            // It's a special ChoiceType field which load options form a Doctrine Entity
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            // To add an Image File
            // Field picturesFiles need to be defined in owner Entity: Property
            ->add('pictureFiles', FileType::class, [
                'required' => false,
                'multiple' => true
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('lat', HiddenType::class)
            ->add('lng', HiddenType::class)
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $outputs = [];
        foreach (Property::HEAT as $k => $v) {
            $outputs[$v] = $k;
        }
        return $outputs;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;


use App\Entity\Contact;
use App\Entity\Property;
use App\Form\ContactType;
use App\Notification\ContactNotification;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;

class PropertyController extends AbstractController
{
    use Controller;

    /**
     * Index All properties page
     * @param Request $request
     * @return Response
     */
    public function index(Request $request): Response
    {
        $propertySearch = new PropertySearch();
        // Handle process in our controller
        $form = $this->createForm(PropertySearchType::class, $propertySearch);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $dataSearch = $form->getData();
            $properties = $this->getPagination(
                $this->repo->findSearchedVisibleQuery($dataSearch),
                $request
            );
        } else {
            $properties = $this->getPagination(
                $this->repo->findAllVisibleQuery(), 
                $request
            );
        }

        return $this->render('property/index.html.twig', [
            'current_nav' => 'properties',
            'form' => $form->createView(),
            'properties' => $properties
        ]);
    }

    /**
     * Show only one property
     * @param Property $property
     * @param Request $request
     * @return Response
     * @ParamConverter("property", class="App\Entity\Property")
     */
    public function show(Property $property, Request $request, ContactNotification $notification): Response
    {
        // ->find() is done automatically by Symfony
        // $property = $this->repo->find($property);

        $contact = new Contact();
        $contact->setProperty($property);

        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $notification->notify($contact);
            $this->addFlash('success', 'Votre email a bien été envoyé');

            return $this->redirectToRoute('property_show', [
                'id' => $property->getId()
            ]);

        }

        return $this->render(
            'property/show.html.twig',
            [
                'current_menu' => 'properties',
                'property' => $property,
                'form' => $form->createView()
            ]
        );
    }

    private function getPagination($repositoryMethod, Request $request)
    {
        return $this->paginator->paginate(
            $repositoryMethod,
            $request->query->getInt('page', 1),
            12
        );
    }
}

templates/property/_property.html.twig
{# A chaque update le cache est mis à jour #}
{#{% cache 'property' ~ property.id property.updatedAt.timestamp %}#}
    <div class="card mb-4">
        {% if property.picture %}
            {# vich_uploader_asset load automatically path to imageFile passed in parameters  #}
            <img src="{{ vich_uploader_asset(property.picture, 'imageFile') | imagine_filter('thumb') }}" alt="Image" class="card-img-top">
        {% endif %}
        <div class="card-body">

            <h5 class="card-title">
                <a href="{{ path('property_show', {id: property.id}) }}">
                    {{ property.title }}
                </a>
            </h5>
            <p class="card-text">{{ property.surface }} m² - {{ property.city }} ({{ property.postalCode }})</p>
            <div class="text-danger">
                {{ property.formattedPrice }} €
            </div>
        </div>
    </div>
{#{% endcache %}#}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All properties{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col">
                    {{ form_row(form.address, {id: 'search_address'}) }}
                </div>
                <div class="col">
                    {{ form_row(form.distance) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <input type="text" placeholder="Adresse" id="search_address" class="form-control">
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="container mt-4">

        <h1>See all of our properties</h1>
        <div class="row">
        {% for property in properties %}
            <div class="col-md-4">
                {% include('property/_property.html.twig') %}
            </div>
        {% endfor %}
        </div>
        
        {{ knp_pagination_render(properties) }}
        
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">

            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}

            {% if not form.vars.valid %}
                <div class="alert alert-danger">
                    Erreur lors de la complétion du formulaire
                </div>
            {% endif %}

            <div class="row">
                <div class="col-md-8">
                    <div data-slider>
                        {% if property.pictures %}
                            {% for picture in property.pictures %}
                                {# vich_uploader_asset load automatically path to imageFile passed in parameters  #}
                                <img src="{{ vich_uploader_asset(picture, 'imageFile') | imagine_filter('medium') }}" alt="Image" class="card-img-top">
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
                    <div class="text-primary" style="font-size: 4rem; font-weight: bold;">
                        {{ property.formattedPrice }}
                    </div>
                    <a href="#" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %} style="display: none;" {% endif %}>Contact agency</a>

                    <div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %}>
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col">{{ form_row(form.firstname) }}</div>
                            <div class="col">{{ form_row(form.lastname) }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form_row(form.phone) }}</div>
                            <div class="col">{{ form_row(form.email) }}</div>
                        </div>
                        {# Display remaining fields #}
                        {{ form_rest(form) }}
                        <div class="form-group">
                            <button class="btn btn-primary">Envoyer</button>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">

        <p>{{ property.description | nl2br }}</p>

        <h2>Features</h2>
        <div class="row">
            <div class="col-md-8">
                <table class="table table-striped">
                    <tr>
                        <td>Livable Surface</td>
                        <td>{{ property.surface }}</td>
                    </tr>
                    <tr>
                        <td>Rooms</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Bedrooms</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Floor</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Heat</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Specificities</h2>
                {% if property.options %}
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">
                            {{ option.name }}
                        </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>

        {# Map part #}
        <div id="map" style="width: 100%; height: 400px" data-lat="{{ property.lat }}" data-lng="{{ property.lng }}"></div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('contactForm') }}
{% endblock %}